### ISSUE TITLE
Installation on Ubuntu 16.04

### ISSUE THREAD

**Issue by RobLoach** [devopsgroup-io/vagrant-hostmanager#196]
Ruby complains...

```
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
/usr/lib/ruby/2.3.0/rubygems/specification.rb:946:in `all=': undefined method `group_by' for nil:NilClass (NoMethodError)
    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:275:in `with_isolated_gem'
    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:231:in `internal_install'
    from /usr/lib/ruby/vendor_ruby/vagrant/bundler.rb:102:in `install'
    from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:62:in `block in install_plugin'
    from /usr/lib/ruby/vendor_ruby/vagrant/plugin/manager.rb:72:in `install_plugin'
    from /usr/share/vagrant/plugins/commands/plugin/action/install_gem.rb:37:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
    from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
    from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
    from /usr/share/vagrant/plugins/commands/plugin/command/base.rb:14:in `action'
    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:32:in `block in execute'
    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `each'
    from /usr/share/vagrant/plugins/commands/plugin/command/install.rb:31:in `execute'
    from /usr/share/vagrant/plugins/commands/plugin/command/root.rb:56:in `execute'
    from /usr/lib/ruby/vendor_ruby/vagrant/cli.rb:42:in `execute'
    from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:268:in `cli'
    from /usr/bin/vagrant:173:in `<main>'
```

**Comment by seth-reeser** [comment]
Try to reinstall after running `sudo rm -Rf ~/.vagrant.d/gems/ && sudo rm ~/.vagrant.d/plugins.json` (you will need to reinstall all of your vagrant plugins)... Also what version of Vagrant do you have installed?

**Comment by RobLoach** [comment]
1.8.3... Will try reinstalling plugins

**Comment by fredw** [comment]
Same problem here. Ruby version:

    ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

**Comment by jgonyea** [comment]
I also had this issue the first time I attempted the plugin installation.  What version of vagrant do you have?  I thought I had installed 1.8.4 (latest), but somehow only 1.8.1 installed on my Ubuntu 16.04 machine.  I re-downloaded the deb file to my ~/Downloads folder and ran the following:
`sudo dpkg -i ~/Downloads/vagrant_1.8.4_x86_64.deb`

This properly upgraded vagrant.  Installing the plugin worked as expected afterwards.

Hope that helps.

**Comment by fredw** [comment]
Thank you @jgonyea. I download and installed the Vagrant 1.8.5 and now vagrant-hostmanager installation worked! The problem was occurring in version 1.8.1, which was standard in Ubuntu 04.16.

**Comment by cmoiccool** [comment]
Same thing here, I upgraded from Vagrant 1.8.1 to Vagrant 1.9.3 (latest for now) and after this installation worked also.

**Comment by jgonyea** [comment]
I think this can be closed. @RobLoach, can you confirm?
