### ISSUE TITLE
Guest hosts files do not get configured with vagrant-hostmanager-1.8.4

### ISSUE THREAD

**Issue by bowlofeggs** [devopsgroup-io/vagrant-hostmanager#209]
Hello! I'm the Fedora package maintainer for vagrant-hostmanager. I was working today on updating Fedora to 1.8.4, and I noticed that the guest in my simple test did not get its hosts file updated with 1.8.4. Fedora 24 currently has 1.8.2 and with that version the guest's hosts file does get updated. FWIW, I am testing with vagrant-libvirt. I noticed that there was some discussion with 1.8.3 that different vagrant backends might not use the same language to describe whether the box is running, so it is possible that this issue is specific to vagrant-libvirt.

Here is a small Vagrantfile I've been testing with:

```
Vagrant.configure(2) do |config|
  config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/23/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-23-20151030.x86_64.vagrant-libvirt.box"
  config.vm.box = "f23-cloud-libvirt"

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true

  config.vm.provision "shell", inline: "cat /etc/hosts"

end
```

When I run that on an F24 box with 1.8.2, the cat command output looks like this:

```
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
==> default: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
==> default: 
==> default: ## vagrant-hostmanager-start
==> default: 192.168.121.248    default
==> default: 
==> default: ## vagrant-hostmanager-end
```

With 1.8.4, it looks like this:

```
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
==> default: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

My guess is that we need some additional string for vagrant-libvirt, similar to what was done in this commit: https://github.com/devopsgroup-io/vagrant-hostmanager/commit/df35eb2a87355f1a97177b0932297b2f5aec0d5b

**Comment by bowlofeggs** [comment]
I am surprised to report that this issue does not occur in 1.8.3. Since 1.8.3 introduced the check for whether the guest was running, I expected it to exhibit this same issue but it does not:

```
[rbarlow@ohm vagrant-testing]$ sudo dnf downgrade vagrant-hostmanager vagrant-hostmanager-doc --enablerepo=updates-testing -y
Fedora 24 - x86_64 - Test Updates                                                                                                                                                                                                              1.2 MB/s | 4.1 MB     00:03    
Last metadata expiration check: 0:00:03 ago on Wed Jul 20 15:17:19 2016.
Dependencies resolved.
===============================================================================================================================================================================================================================================================================
 Package                                                                    Arch                                                      Version                                                         Repository                                                          Size
===============================================================================================================================================================================================================================================================================
Downgrading:
 vagrant-hostmanager                                                        noarch                                                    1.8.3-1.fc24                                                    updates-testing                                                     18 k
 vagrant-hostmanager-doc                                                    noarch                                                    1.8.3-1.fc24                                                    updates-testing                                                    254 k

Transaction Summary
===============================================================================================================================================================================================================================================================================
Downgrade  2 Packages

Total download size: 273 k
Downloading Packages:
(1/2): vagrant-hostmanager-1.8.3-1.fc24.noarch.rpm                                                                                                                                                                                              67 kB/s |  18 kB     00:00    
(2/2): vagrant-hostmanager-doc-1.8.3-1.fc24.noarch.rpm                                                                                                                                                                                         331 kB/s | 254 kB     00:00    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                                                                                          207 kB/s | 273 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Downgrading : vagrant-hostmanager-1.8.3-1.fc24.noarch                                                                                                                                                                                                                    1/4 
  Downgrading : vagrant-hostmanager-doc-1.8.3-1.fc24.noarch                                                                                                                                                                                                                2/4 
  Erasing     : vagrant-hostmanager-doc-1.8.4-1.fc24.noarch                                                                                                                                                                                                                3/4 
  Erasing     : vagrant-hostmanager-1.8.4-1.fc24.noarch                                                                                                                                                                                                                    4/4 
  Verifying   : vagrant-hostmanager-1.8.3-1.fc24.noarch                                                                                                                                                                                                                    1/4 
  Verifying   : vagrant-hostmanager-doc-1.8.3-1.fc24.noarch                                                                                                                                                                                                                2/4 
  Verifying   : vagrant-hostmanager-1.8.4-1.fc24.noarch                                                                                                                                                                                                                    3/4 
  Verifying   : vagrant-hostmanager-doc-1.8.4-1.fc24.noarch                                                                                                                                                                                                                4/4 

Downgraded:
  vagrant-hostmanager.noarch 1.8.3-1.fc24                                                                                              vagrant-hostmanager-doc.noarch 1.8.3-1.fc24                                                                                             

You should restart:
  Nothing needs to be restarted
Complete!
[rbarlow@ohm vagrant-testing]$ vagrant destroy
==> default: Removing domain...
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)...
[rbarlow@ohm vagrant-testing]$ time vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant-testing_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          f23-cloud-libvirt
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/vagrant-testing_default.img (41G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/rbarlow/devel/vagrant-testing/ => /vagrant
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
==> default: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
==> default: 
==> default: ## vagrant-hostmanager-start
==> default: 192.168.121.225    default
==> default: 
==> default: ## vagrant-hostmanager-end

real    0m14.083s
user    0m1.227s
sys     0m0.169s
[rbarlow@ohm vagrant-testing]$ rpm -q vagrant-hostmanager
vagrant-hostmanager-1.8.3-1.fc24.noarch
```

**Comment by bowlofeggs** [comment]
I am not very familiar with Ruby, but is it possible that the ```if state.short_description.eql? 'active' || 'running'``` line has an order of precedence issue? Is the ```'active' || 'running'``` bit evaluated before the eql?

**Comment by bowlofeggs** [comment]
I don't know Ruby very well, but I think https://github.com/devopsgroup-io/vagrant-hostmanager/commit/df35eb2a87355f1a97177b0932297b2f5aec0d5b has an order of precedence problem. I did a little Ruby experiment to check it out:

```
$ irb
irb(main):001:0> "hello".eql? "hello" || "goodbye"
=> true
irb(main):002:0> "hello".eql? "goodbye" || "hello"                                                                                     
=> false
```

Perhaps we need two ```.eql?``` statements on either side of the ```||``` operator?

**Comment by seth-reeser** [comment]
Hi @bowlofeggs ! First off, thank you and everyone at Fedora for maintaining dnf, we appreciate it! You are correct, I've pushed a bugfix - can you please verify for me? Thank you

**Comment by bowlofeggs** [comment]
Hey @seth-reeser! I should also thank you for writing and maintaining vagrant-hostmanager. It's a useful plugin and it helps me almost every day!

I just did a scratch build of 1.8.5 for F24 and it does seem to fix this issue. Thanks for the amazing turn around time!

```
[rbarlow@ohm vagrant-testing]$ sudo dnf install -y https://kojipkgs.fedoraproject.org//work/tasks/927/14960927/vagrant-hostmanager-1.8.5-1.fc24.noarch.rpm https://kojipkgs.fedoraproject.org//work/tasks/927/14960927/vagrant-hostmanager-doc-1.8.5-1.fc24.noarch.rpm
Last metadata expiration check: 0:35:11 ago on Wed Jul 20 15:45:06 2016.
Dependencies resolved.
===============================================================================================================================================================================================================================================================================
 Package                                                                    Arch                                                      Version                                                            Repository                                                       Size
===============================================================================================================================================================================================================================================================================
Upgrading:
 vagrant-hostmanager                                                        noarch                                                    1.8.5-1.fc24                                                       @commandline                                                     17 k
 vagrant-hostmanager-doc                                                    noarch                                                    1.8.5-1.fc24                                                       @commandline                                                    253 k

Transaction Summary
===============================================================================================================================================================================================================================================================================
Upgrade  2 Packages

Total size: 271 k
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Upgrading   : vagrant-hostmanager-1.8.5-1.fc24.noarch                                                                                                                                                                                                                    1/4 
  Upgrading   : vagrant-hostmanager-doc-1.8.5-1.fc24.noarch                                                                                                                                                                                                                2/4 
  Cleanup     : vagrant-hostmanager-doc-1.8.3-1.fc24.noarch                                                                                                                                                                                                                3/4 
  Cleanup     : vagrant-hostmanager-1.8.3-1.fc24.noarch                                                                                                                                                                                                                    4/4 
  Verifying   : vagrant-hostmanager-doc-1.8.5-1.fc24.noarch                                                                                                                                                                                                                1/4 
  Verifying   : vagrant-hostmanager-1.8.5-1.fc24.noarch                                                                                                                                                                                                                    2/4 
  Verifying   : vagrant-hostmanager-1.8.3-1.fc24.noarch                                                                                                                                                                                                                    3/4 
  Verifying   : vagrant-hostmanager-doc-1.8.3-1.fc24.noarch                                                                                                                                                                                                                4/4 

Upgraded:
  vagrant-hostmanager.noarch 1.8.5-1.fc24                                                                                              vagrant-hostmanager-doc.noarch 1.8.5-1.fc24                                                                                             

You should restart:
  Nothing needs to be restarted
Complete!
[rbarlow@ohm vagrant-testing]$ vagrant destroy
==> default: Removing domain...
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)...
[rbarlow@ohm vagrant-testing]$ cat /etc/hosts
10.13.129.77 planck.usersys.redhat.com planck

127.0.0.1               localhost.localdomain localhost ohm ohm.usersys.redhat.com
::1             localhost6.localdomain6 localhost6

192.168.100.217 boole.localdomain boole
[rbarlow@ohm vagrant-testing]$ time vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              vagrant-testing_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              1
==> default:  -- Memory:            512M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          f23-cloud-libvirt
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/vagrant-testing_default.img (41G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:67:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
/usr/share/gems/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:84:in `initialize': Object#timeout is deprecated, use Timeout.timeout instead.
==> default: Configuring and enabling network interfaces...
==> default: Rsyncing folder: /home/rbarlow/devel/vagrant-testing/ => /vagrant
==> default: Updating /etc/hosts file on active guest machines...
==> default: Updating /etc/hosts file on host machine (password may be required)...
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
==> default: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
==> default: 
==> default: ## vagrant-hostmanager-start
==> default: 192.168.121.168    default
==> default: 
==> default: ## vagrant-hostmanager-end

real    0m15.080s
user    0m1.217s
sys     0m0.184s
[rbarlow@ohm vagrant-testing]$ cat /etc/hosts
10.13.129.77 planck.usersys.redhat.com planck

127.0.0.1               localhost.localdomain localhost ohm ohm.usersys.redhat.com
::1             localhost6.localdomain6 localhost6

192.168.100.217 boole.localdomain boole

## vagrant-hostmanager-start id: 01761c83-570c-4698-994d-708c72c1d51e
192.168.121.168 default

## vagrant-hostmanager-end
```

**Comment by seth-reeser** [comment]
Fantastic! Let us know if you run into anything else.
