### ISSUE TITLE
Unable to install on Vagrant 1.9.5

### ISSUE THREAD

**Issue by btantlinger** [devopsgroup-io/vagrant-hostmanager#237]
Running Arch Linux with vagrant 1.9.5-1 and vagrant-substrate 605.0566498-2.  Installing hostmanager with vagrant plugin install fails.  Output below.

```
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
/opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/source.rb:192:in `load': Marshal.load reentered at marshal_load (RuntimeError)
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/source.rb:192:in `load_specs'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:335:in `block in validate_configured_sources!'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/source_list.rb:97:in `each'
        from /opt/vagrant/embedded/lib/ruby/2.2.0/rubygems/source_list.rb:97:in `each_source'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:333:in `validate_configured_sources!'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:268:in `internal_install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/bundler.rb:106:in `install'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:62:in `block in install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:72:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/plugin/manager.rb:72:in `install_plugin'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/action/install_gem.rb:29:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/base.rb:14:in `action'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:32:in `block in execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:31:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/install.rb:31:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/plugins/commands/plugin/command/root.rb:66:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/cli.rb:42:in `execute'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/lib/vagrant/environment.rb:308:in `cli'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.9.5/bin/vagrant:138:in `<main>'

```

**Comment by btantlinger** [comment]
Nevermind, seems to be an issue with vagrant on arch linux...
