### ISSUE TITLE
Provision with hostmanager randomly fails

### ISSUE THREAD

**Issue by pkaramol** [devopsgroup-io/vagrant-hostmanager#271]
I am creating a `vagrant` environment using `make`

Here is the `make` target

```
make mongodb:
	vagrant plugin install vagrant-hostmanager
	VAGRANT_VAGRANTFILE=Vagrantfile_MongoDB 
	vagrant destroy -f 
	vagrant up --provision
```

This fails randomly.

In some cases it will halt as follows:

```
(master)*$ make mongodb 
vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.9)'!
VAGRANT_VAGRANTFILE=Vagrantfile_MongoDB 
vagrant destroy -f 
==> mongodb_secondary_2: VM not created. Moving on...
==> mongodb_secondary_1: VM not created. Moving on...
==> mongodb_primary_1: Forcing shutdown of VM...
==> mongodb_primary_1: Destroying VM and associated drives...
==> mongodb_primary_1: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> mongodb_primary_1: [vagrant-hostmanager:host] Updating hosts file on your workstation (password may be required)...
Makefile:2: recipe for target 'mongodb' failed
make: *** [mongodb] Error 2
```

In other it will proceed as expected.

```
$ cat /etc/sudoers.d/vagrant_hostmanager 
Cmnd_Alias VAGRANT_HOSTMANAGER_UPDATE = /bin/cp /home/pkara/.vagrant.d/tmp/hosts.local /etc/hosts
%sudo ALL=(root) NOPASSWD: VAGRANT_HOSTMANAGER_UPDATE
```

My only relevant lines in the corresponding `Vagrantfile` are:

```
Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

```

and on each vm being provisioned:

```
 config.vm.define "foobar" do |something|
    something.vm.hostname = "some.hostname"
    something.vm.network "private_network", ip: "192.168.33.10"
    something.vm.provision "hostmanager"

  end
```

**Comment by pkaramol** [comment]
Enabling debug mode on `vagrant` does not show any extra info on these steps.

**Comment by seth-reeser** [comment]
Does your workstation `/etc/hosts` file get updated? What happens when you run your `make` script commands manually? My guess is there is a prompt for a password that you're not seeing.

https://stackoverflow.com/questions/20671511/how-do-i-get-make-to-prompt-the-user-for-a-password-and-store-it-in-a-makefile/20671804

**Comment by pkaramol** [comment]
Yes `/etc/hosts` at some point in time did get updated.
I will try to run the commands manually and get back to you; I have a hunch that it may be the `vagrant destroy -f` that causes the problem.

**Comment by pkaramol** [comment]
Yes `/etc/hosts` at some point in time did get updated.
I will try to run the commands manually and get back to you; I have a hunch that it may be the `vagrant destroy -f` that causes the problem.

**Comment by pkaramol** [comment]
Here is a manual run of the command(s)

```
(master)*$ vagrant destroy -f && vagrant up --provision
==> kubernetes-node-2: VM not created. Moving on...
==> kubernetes-node-1: You assigned a static IP ending in ".1" to this machine.
==> kubernetes-node-1: This is very often used by the router and can cause the
==> kubernetes-node-1: network to not work properly. If the network doesn't work
==> kubernetes-node-1: properly, try changing this IP.
==> kubernetes-node-1: You assigned a static IP ending in ".1" to this machine.
==> kubernetes-node-1: This is very often used by the router and can cause the
==> kubernetes-node-1: network to not work properly. If the network doesn't work
==> kubernetes-node-1: properly, try changing this IP.
==> kubernetes-node-1: Forcing shutdown of VM...
==> kubernetes-node-1: Destroying VM and associated drives...
==> kubernetes-node-1: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> kubernetes-node-1: [vagrant-hostmanager:host] Updating hosts file on your workstation (password may be required)...
==> kubernetes-master-1: You assigned a static IP ending in ".1" to this machine.
==> kubernetes-master-1: This is very often used by the router and can cause the
==> kubernetes-master-1: network to not work properly. If the network doesn't work
==> kubernetes-master-1: properly, try changing this IP.
==> kubernetes-master-1: You assigned a static IP ending in ".1" to this machine.
==> kubernetes-master-1: This is very often used by the router and can cause the
==> kubernetes-master-1: network to not work properly. If the network doesn't work
==> kubernetes-master-1: properly, try changing this IP.
==> kubernetes-master-1: Forcing shutdown of VM...
==> kubernetes-master-1: Destroying VM and associated drives...
==> kubernetes-master-1: [vagrant-hostmanager:guests] Updating hosts file on active guest virtual machines...
==> kubernetes-master-1: [vagrant-hostmanager:host] Updating hosts file on your workstation (password may be required)...
```


On a second run, it succeeds;

I never have had to enter password so far.

It just sometimes fail and some other times succeeds;

In order for it to fail though, at least one `vagrant` VM should be in `running` state;

Does this make sense?

**Comment by nikhil-shetye-239** [comment]
Hi 

I am getting below issue while vagrant up command

 db01: [vagrant-hostmanager:host] Updating hosts file on your workstation (password may be required)...
Traceback (most recent call last):
        159: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        158: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:203:in `action'
        157: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:203:in `call'
        156: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/environment.rb:631:in `lock'
        155: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:217:in `block in action'
        154: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/machine.rb:248:in `action_raw'
        153: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
        152: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
        151: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
        150: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
        149: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        148: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        147: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        146: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        145: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
        144: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
        143: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
        142: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
        141: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        140: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        139: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        138: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        137: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        136: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        135: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        134: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        133: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        132: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:53:in `call'
        131: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
        130: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
        129: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
        128: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
        127: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        126: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        125: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        124: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
        123: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        122: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/customize.rb:40:in `call'
        121: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        120: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/prepare_clone.rb:15:in `call'
        119: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        118: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/prepare_clone_snapshot.rb:17:in `call'
        117: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        116: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/import.rb:13:in `call'
        115: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/import.rb:78:in `import'
        114: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        113: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/discard_state.rb:15:in `call'
        112: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        111: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/match_mac_address.rb:22:in `call'
        110: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        109: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        108: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        107: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
        106: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        105: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        104: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        103: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        102: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
        101: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/box_check_outdated.rb:93:in `call'
        100: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         99: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:53:in `call'
         98: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
         97: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
         96: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
         95: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
         94: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         93: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         92: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         91: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:53:in `call'
         90: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
         89: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
         88: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
         87: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
         86: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         85: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         84: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         83: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:53:in `call'
         82: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `run'
         81: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/busy.rb:19:in `busy'
         80: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/runner.rb:101:in `block in run'
         79: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builder.rb:180:in `call'
         78: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         77: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
         76: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         75: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
         74: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         73: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:26:in `call'
         72: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         71: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/set_name.rb:50:in `call'
         70: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         69: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in `call'
         68: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         67: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/provision.rb:80:in `call'
         66: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         65: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
         64: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         63: from C:/Users/ASUS/.vagrant.d/gems/2.7.6/gems/vagrant-hostmanager-1.8.10/lib/vagrant-hostmanager/action/update_all.rb:27:in `call'
         62: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         61: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/env_set.rb:19:in `call'
         60: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         59: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in `call'
         58: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         57: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:52:in `call'
         56: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         55: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in `call'
         54: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         53: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/synced_folders/nfs/action_cleanup.rb:19:in `call'
         52: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         51: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
         50: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         49: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/delayed.rb:19:in `call'
         48: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         47: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
         46: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         45: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/prepare_nfs_settings.rb:19:in `call'
         44: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         43: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/set_default_nic_type.rb:64:in `call'
         42: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         41: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/clear_network_interfaces.rb:26:in `call'
         40: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         39: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/network.rb:148:in `call'
         38: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         37: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/network_fix_ipv6.rb:41:in `call'
         36: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         35: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/forward_ports.rb:31:in `call'
         34: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         33: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/set_hostname.rb:17:in `call'
         32: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         31: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action/sane_defaults.rb:38:in `call'
         30: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/warden.rb:48:in `call'
         29: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/call.rb:47:in `call'
         28: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/plugins/providers/virtualbox/action.rb:84:in `block (2 levels) in action_boot'
         27: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         26: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         25: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/action/builtin/cloud_init_setup.rb:1:in `<top (required)>'
         24: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         23: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         22: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/vagrant-2.3.4/lib/vagrant/util/mime.rb:1:in `<top (required)>'
         21: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         20: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         19: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types.rb:233:in `<top (required)>'
         18: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         17: from C:/HashiCorp/Vagrant/embedded/mingw64/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
         16: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/registry.rb:88:in `<top (required)>'
         15: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/registry.rb:89:in `<class:Types>'
         14: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/registry.rb:69:in `load_default_mime_types'
         13: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/loader.rb:93:in `load'
         12: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/loader.rb:84:in `load'
         11: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/loader.rb:72:in `load_columnar'
         10: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:25:in `load_base_data'
          9: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:42:in `each_file_line'
          8: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:42:in `synchronize'
          7: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:48:in `block in each_file_line'
          6: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:48:in `each'
          5: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:55:in `block (2 levels) in each_file_line'
          4: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types/_columnar.rb:33:in `block in load_base_data'
          3: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types.rb:168:in `add'
          2: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/types.rb:168:in `=='
          1: from C:/HashiCorp/Vagrant/embedded/gems/2.3.4/gems/mime-types-3.4.1/lib/mime/type.rb:175:in `<=>'
C:/Users/ASUS/.vagrant.d/gems/2.7.6/gems/rubyhacks-0.1.5/lib/rubyhacks.rb:361:in `<=>': undefined method `old_compare' for nil:NilClass (NoMethodError)
